[package]
name = "day23"
version = "0.1.0"
authors = ["Anders Åstrand <aastrand@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
